INSERT INTO PERSON (ID, NAME, TEMPORARY_ADDRESS_ID, PERMANENT_ADDRESS_ID, CREATE_DATE) VALUES (1, 'Jeff', null, 1, '2022-04-11');
INSERT INTO ADDRESS (ID, COUNTRY, CITY, ZIP, STREET, CREATE_DATE) VALUES (1, 'Hungary', 'Budapest', '1111', 'Test street', '2022-04-11');
INSERT INTO CONTACT (ID, CONTACT_TYPE, DATA, ADDRESS_ID, CREATE_DATE) VALUES (1, 'MOBILE_PHONE', '0630300000', 1, '2022-04-11');
INSERT INTO CONTACT (ID, CONTACT_TYPE, DATA, ADDRESS_ID, CREATE_DATE) VALUES (2, 'EMAIL', 'test@test.com', 1, '2022-04-11');

INSERT INTO PERSON (ID, NAME, TEMPORARY_ADDRESS_ID, PERMANENT_ADDRESS_ID, CREATE_DATE) VALUES (2, 'Ana', 2, 3, '2022-04-11');
INSERT INTO ADDRESS (ID, COUNTRY, CITY, ZIP, STREET, CREATE_DATE) VALUES (2, 'Hungary', 'Budapest', '1000', 'Other Test street', '2022-04-11');
INSERT INTO ADDRESS (ID, COUNTRY, CITY, ZIP, STREET, CREATE_DATE) VALUES (3, 'Hungary', 'Budapest', '1122', 'Another Test street', '2022-04-11');
INSERT INTO CONTACT (ID, CONTACT_TYPE, DATA, ADDRESS_ID, CREATE_DATE) VALUES (3, 'MOBILE_PHONE', '0620300022', 2, '2022-04-11');
INSERT INTO CONTACT (ID, CONTACT_TYPE, DATA, ADDRESS_ID, CREATE_DATE) VALUES (4, 'EMAIL', 'test.ana@tests.hu', 2, '2022-04-11');
INSERT INTO CONTACT (ID, CONTACT_TYPE, DATA, ADDRESS_ID, CREATE_DATE) VALUES (5, 'EMAIL', 'ana.test@test.com', 3, '2022-04-11');