spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/KesmarkiDB
    username: postgres
    password: password
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml