spring:
  datasource:
    # in normal circumstances these would be collected from an environment specific secret
    # change these to ms sql for testing
    url: jdbc:postgresql://localhost:5432/KesmarkiDB
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
application:
  validation:
    stringLength: 255